version: "3.9"

x-common-variables: &common-variables
  SNSCRAPE_TWITTER_USERS: granblue_en,granbluefantasy
  SNSCRAPE_DATABASE_DB: twitter
  SNSCRAPE_DATABASE_HOST: postgres
  SNSCRAPE_DATABASE_USERNAME: postgres
  SNSCRAPE_DATABASE_PASSWORD: sample_password

services:
  discord-bot:
    image: catfacts/song
    build:
      context: ./song
    environment:
      <<: *common-variables
      DISCORD_TOKEN:
      DISCORD_NEWS_CHANNEL_ID:
      DISCORD_COMMAND_PREFIX: ","
      # Can replace the TWITTER_BASE_URL with a different twitter base, such as
      # fxtwitter.com or vxtwitter.com
      TWITTER_BASE_URL: "twitter.com"
    depends_on:
      scraper:
        condition: service_healthy

  scraper:
    image: catfacts/twitter-scraper
    build:
      context: ./scraper
    environment: *common-variables
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/home/song/healthcheck.sh"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 20s

  postgres:
    image: postgres:14-alpine
    restart: always
    user: postgres
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: sample_password
    hostname: postgres
    volumes:
      - pgdata:/var/lib/postgresql/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: