version: "3.9"

x-common-variables: &common-variables
  SNSCRAPE_TWITTER_USERS: granblue_en,granbluefantasy
  SNSCRAPE_DATABASE_DB: twitter
  SNSCRAPE_DATABASE_HOST: postgres
  SNSCRAPE_DATABASE_USERNAME: postgres
  SNSCRAPE_DATABASE_PASSWORD: sample_password

services:
  discord-bot:
    image: catfacts/song
    build:
      context: ./song
    environment:
      <<: *common-variables
      DISCORD_TOKEN:
      DISCORD_NEWS_CHANNEL_ID:
      DISCORD_COMMAND_PREFIX: ","
      # Can replace the TWITTER_BASE_URL with a different twitter base, such as
      # fxtwitter.com or vxtwitter.com
      TWITTER_BASE_URL: "twitter.com"
    depends_on:
      - scraper
      - postgres

  scraper:
    image: catfacts/twitter-scraper
    build:
      context: ./scraper
    environment: *common-variables
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: sample_password
    hostname: postgres
    volumes:
      - pgdata:/var/lib/postgresql/pgdata

volumes:
  pgdata: